import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Noto_Sans_KR} from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';


const inter = Inter({ subsets: ['latin'] })
const noto = Noto_Sans_KR({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'percyLN preview',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={noto.className}>{children}<Analytics/></body>
    </html>
  )
}
